name: "CodeQL"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CodeQL
        uses: github/codeql-action/setup-codeql@v1

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Analyze code
        uses: github/codeql-action/analyze@v1
